name: ML Pipeline (Self-Hosted Runner)

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  train:
    runs-on: self-hosted
    name: Train Model on Custom Machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          python -m venv venv
          ./venv/Scripts/activate
          pip install --upgrade pip
          pip install -r req.txt

      - name: Run Data Cleaning and Model Training
        run: |
          ./venv/Scripts/activate
          python app/resources/data_clean.py
          python app/resources/train.py

      - name: Save Models
        run: |
          mkdir -p saved_models
          cp -r models/* saved_models/ || echo "No models found"

      - name: Upload Models (optional)
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: saved_models/
